config/routes.rb
Rails.application.routes.draw do
  resources :gitissues
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gitissue.rb
class Gitissue
  include Mongoid::Document
  field :name, type: String
  field :content, type: String
  field :link, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gitissues_controller.rb
require 'net/http'
require 'json'

require 'open-uri'
require 'json'

class GitissuesController < ApplicationController
  before_action :set_gitissue, only: [:show, :edit, :update, :destroy]

  # GET /gitissues
  # GET /gitissues.json
  def index
    a = URI.parse("https://api.github.com/repos/nnluukhtn/employment_bot/issues?state=all").read
    @gitissue = JSON.parse(a)
  end

  # GET /gitissues/1
  # GET /gitissues/1.json
  def show
  end

  # GET /gitissues/new
  def new
    @gitissue = Gitissue.new
  end

  # GET /gitissues/1/edit
  def edit
  end

  # POST /gitissues
  # POST /gitissues.json
  def create
    @gitissue = Gitissue.new(gitissue_params)

    respond_to do |format|
      if @gitissue.save
        format.html { redirect_to @gitissue, notice: 'Gitissue was successfully created.' }
        format.json { render :show, status: :created, location: @gitissue }
      else
        format.html { render :new }
        format.json { render json: @gitissue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gitissues/1
  # PATCH/PUT /gitissues/1.json
  def update
    respond_to do |format|
      if @gitissue.update(gitissue_params)
        format.html { redirect_to @gitissue, notice: 'Gitissue was successfully updated.' }
        format.json { render :show, status: :ok, location: @gitissue }
      else
        format.html { render :edit }
        format.json { render json: @gitissue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gitissues/1
  # DELETE /gitissues/1.json
  def destroy
    @gitissue.destroy
    respond_to do |format|
      format.html { redirect_to gitissues_url, notice: 'Gitissue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gitissue
      @gitissue = Gitissue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gitissue_params
      params.require(:gitissue).permit(:name, :content, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gitissues_helper.rb
module GitissuesHelper
end

app/views/gitissues/_form.html.erb
<%= form_with(model: gitissue, local: true) do |form| %>
  <% if gitissue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gitissue.errors.count, "error") %> prohibited this gitissue from being saved:</h2>

      <ul>
      <% gitissue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gitissues/edit.html.erb
<h1>Editing Gitissue</h1>

<%= render 'form', gitissue: @gitissue %>

<%= link_to 'Show', @gitissue %> |
<%= link_to 'Back', gitissues_path %>

app/views/gitissues/index.html.erb
<%= react_component("Git", {gitissue: @gitissue}, :class => 'for-table-posts') %>

app/views/gitissues/new.html.erb
<h1>New Gitissue</h1>

<%= render 'form', gitissue: @gitissue %>

<%= link_to 'Back', gitissues_path %>

app/views/gitissues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gitissue.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @gitissue.content %>
</p>

<p>
  <strong>Link:</strong>
  <%= @gitissue.link %>
</p>

<%= link_to 'Edit', edit_gitissue_path(@gitissue) %> |
<%= link_to 'Back', gitissues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-no-turbolink': 'reload' %>
    <%= javascript_include_tag 'application', 'data-no-turbolink': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>